# Generated by Django 6.0.2 on 2026-02-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_spotifytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
