# Generated by Django 6.0.2 on 2026-03-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
