# Generated by Django 6.0.2 on 2026-04-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="visibility",
            field=models.CharField(default="private", max_length=10),
        ),
    ]
