# Generated by Django 6.0.2 on 2026-04-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_playlist_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="danceability",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="energy",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="happiness",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="history_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playlist",
            name="location_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="playlist",
            name="weather_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="playlist",
            name="weather_used",
            field=models.BooleanField(default=False),
        ),
    ]
