# Generated by Django 6.0.2 on 2026-04-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_feedback_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
