# Generated by Django 6.0.2 on 2026-04-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_playlist_danceability_playlist_energy_and_more'),
        ('users', '0011_alter_user_role_delete_feedback'),
    ]

    operations = [
    ]
