# Generated by Django 6.0.2 on 2026-04-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_restore_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
